name: Main Workflow
on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: jcp99gamers/Author-Prisha-Chawla
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run script
        run: python main.py
        working-directory: ./output
      - name: Commit changes
        run: |
          git config user.name "jcp99gamers"
          git config user.email "jcp99gamer@gmail.com"
          git add README.md
          git commit -m "Update README.md"
          git push
        working-directory: ./output
        env:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
