name: Main Workflow
on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Git
        run: sudo apt-get install git
      - name: Set up Git
        run: |
          git config --global user.name "jcp99gamers"
          git config --global user.email "jcp99gamer@gmail.com"
          git config --global credential.helper store
          git clone https://jcp99gamers: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@github.com/jcp99gamers/Author-Prisha-Chawla.git
          cd your-repository
          git checkout main
          git remote set-url origin https://jcp99gamers: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@github.com/jcp99gamers/Author-Prisha-Chawla.git
          git fetch origin main
          git pull origin main
          git checkout main
          git config --global user.email "jcp99gamer@gmail.com"
          echo "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" | git credential-store --store= --file=.git/credentials store
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run script
        run: python main.py
        working-directory: ./output